[package]
name = "ecoscope-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
ecoscope-core = { path = "../ecoscope-core" }
ecoscope-rerun = { path = "../ecoscope-rerun" }
ecoscope-service = { path = "../ecoscope-service" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true
webbrowser.workspace = true

[dev-dependencies]
tempfile.workspace = true
