[package]
name = "wilddatum-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
copc-rs.workspace = true
blake3.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
csv.workspace = true
directories.workspace = true
wilddatum-core = { path = "../wilddatum-core" }
wilddatum-local-import = { path = "../wilddatum-local-import" }
wilddatum-query = { path = "../wilddatum-query" }
flatgeobuf.workspace = true
geo.workspace = true
geojson.workspace = true
geotiff-reader.workspace = true
geotiff-writer.workspace = true
geozero.workspace = true
hdf5-metno.workspace = true
image.workspace = true
las.workspace = true
ndarray.workspace = true
netcdf3.workspace = true
parquet.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
shapefile.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
wkt.workspace = true
zarrs.workspace = true

[dev-dependencies]
arrow-ipc.workspace = true
